# Generated by Django 3.2.16 on 2022-12-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('wavelength', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('cube', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('metadata', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaskImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('linkimage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='hsi.binaryimages')),
            ],
        ),
    ]
