# Generated by Django 3.2.16 on 2022-12-01 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annot_file_type', models.CharField(max_length=2048, verbose_name='Annotation File Type')),
                ('annot_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HSISoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsi_software_name', models.CharField(default='Senope', max_length=2048, verbose_name='Software Name')),
                ('hsi_software_version', models.CharField(max_length=2048, verbose_name='Software version')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_filename', models.CharField(max_length=2048, verbose_name='Mask filename')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsi.annotation')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_type', models.CharField(max_length=2048, verbose_name='Acquisition Type')),
                ('light_source_desc', models.CharField(choices=[('Xenon', 'Xenon'), ('Blue400', 'Blue400'), ('Yellow500', 'Yellow500')], max_length=2048, verbose_name='Light Source Description')),
                ('light_intensity', models.IntegerField()),
                ('optic_imaging_system', models.CharField(default='Pentero 900', max_length=2048, verbose_name='Optic Imaging System')),
                ('hsi_camera_name', models.CharField(default='Senop HSC-2', max_length=2048, verbose_name='Camera Name')),
                ('hsi_adapter_name', models.CharField(max_length=2048, verbose_name='HSI Adapter Name')),
                ('reference', models.CharField(choices=[('Reflectance', 'Reflectance'), ('Absorbance', 'Absorbance')], max_length=2048, verbose_name='Reference')),
                ('environment_desc', models.CharField(choices=[('OR301', 'Or301'), ('OR302', 'Or302'), ('OR303', 'Or303'), ('Wetlab', 'Wetlab')], max_length=2048, verbose_name='Environment Description')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsi.hsisoftware')),
            ],
        ),
        migrations.CreateModel(
            name='HSIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsi_id', models.IntegerField(unique=True)),
                ('hsi_filename', models.CharField(max_length=2048, verbose_name='Filename')),
                ('creation_timestamp', models.TimeField(auto_now_add=True)),
                ('last_update_timestamp', models.TimeField(auto_now=True)),
                ('bandpass_min', models.IntegerField()),
                ('bandpass_max', models.IntegerField()),
                ('hsi_height', models.IntegerField()),
                ('hsi_width', models.IntegerField()),
                ('hsi_bands', models.IntegerField()),
                ('frames', models.IntegerField()),
                ('data_size', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsi.patient')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsi.imagingsettings')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='hsi_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hsi.hsiimage'),
        ),
    ]
